INT = {
    "BROWSER": "chrome",
    "DELAY": "1",
    "LOGIN_URL": "https://tsc.int.itservices.lan/",
    "BSCSID":"1.20001014",
    "VALID_USERNAME": "mark.rijsdijk@t-mobile.nl",
    "VALID_PASSWORD": "Abcd1234",
    "INVALID_USERNAME": "abc@t-mobile.com",
    "INVALID_PASSWORD": "qwerty123",
    "FIRST_NAME": "Mathéo",
    "BASIC_FO_LAST_NAME": "Mátyás",
    "Update_BASIC_FO_LAST_NAME": "Agnès",
    "BASIC_MO_LAST_NAME": "Hölmö",
    "BASIC_FMC_LAST_NAME": "Özcan",
    "IVR_NAME": "IVR Jokūbas",
    "Update_IVR_NAME": "IVR Agnès",
    "HG_NAME": "HG KŠthe",
    "Update_HG_NAME": "HG Asbjørn",
    "FLEX_DEVICE_NAME": "FLEX Van Buren",
    "Update_FLEX_DEVICE_NAME": "FLEX váńbúŕéń",
    "DEVICE_NAME": "DECT d3(7",
    "Update_DECT_DEVICE_NAME": "DECT Renée",
    "FAX_NAME": "FAX Noël",
    "Update_FAX_NAME": "FAX Sørina",
    "CC_NAME": "CC François",
    "Update_CC_NAME": "CC Mary-Jo",
    "PASSWORD": "ABcd@#123456",
    "Update_PASSWORD": "ABcd@#456789",
    "COUNT": "9040",
    "BP_URL":"https://tsc.int.itservices.lan/hv/service",
    "MainURL":"https://tsc.int.itservices.lan/hv/groups",
    "USER_TAB": "https://tsc.int.itservices.lan/hv/groups/174163477/users",
    "IVR_TAB": "https://tsc.int.itservices.lan/hv/groups/174163477/ivrs",
    "HG_TAB": "https://tsc.int.itservices.lan/hv/groups/174163477/hunt_groups",
    "FLEX_TAB": "https://tsc.int.itservices.lan/hv/groups/174163477/flex",
    "FAX_TAB": "https://tsc.int.itservices.lan/hv/groups/174163477/fax_to_emails",
    "CC_TAB": "https://tsc.int.itservices.lan/hv/groups/174163477/call_centers",
    "DECT_TAB": "https://tsc.int.itservices.lan/hv/groups/174163477/multi_user_devices",
    "GROUP_TAB": "https://tsc.int.itservices.lan/hv/groups/174163477/group_settings",
    "BASE_URL": "https://eoc.int.itservices.lan/eoc/uws/v1/order",
    "OrderLink": "https://eoc-om.int.itservices.lan/om/#/order",
    "createOrderURLGRP": "https://eoc.int.itservices.lan/eoc/serviceOrderingManagement/v1",
    "SR_URL": "https://eoc.int.itservices.lan/eoc/sr/v1/service",
    "EAI_URL": "https://eai.int.itservices.lan/oss-core-ws/rest/inv",
    "reservationPoolURL": "https://eai.int.itservices.lan/oss-core-ws/rest/tmfnm-adv/ResourcePoolManagement",
    "eaiPortOut": "https://eai.int.itservices.lan/oss-core-ws/rest",
    "createOrderURL": "https://eoc.int.itservices.lan/eoc",
    "enumCheckURL": "http://mw.int.itservices.lan:5180/rest/VTEOC/Incoming/Flows/Routing",
    "numberStatusCheckURL": "https://eai.int.itservices.lan/oss-core-ws/rest/onm/listnm",
    "CHECK_WORKFLOW_URL": "https://eoc.int.itservices.lan/eoc/uws/v1/fpi",
    "eaiNumberCheckURL": "https://eai.int.itservices.lan/oss-core-ws/rest/onm/number",
    "MessageLogURL": "https://eoc.int.itservices.lan/eoc/logManagement/v1",
    "ErrorStatusLogURL": "https://eoc.int.itservices.lan/eoc/logManagement/v1",
    "BROADSOFT_URL": "https://nr-workers-staging.itservices.lan/api/Voice/v1",
    "ACISION_URL": "https://nr-workers-staging.itservices.lan/api/Voicemail/v1",
    "numberCheckEAI": "https://eai.int.itservices.lan/oss-core-ws/rest/onm/number",
    "eaiReservationURL": "https://eai.int.itservices.lan/oss-core-ws/rest/tmfnm-adv",
    "CHECK_ORDER_URL": "https://eoc.int.itservices.lan/eoc/uws/v1/order",
    "AUTHORIZATION": "Basic c3ZjX2NvbXVzZXI6ZXFDU0NxPmU4Iw==",
    "authEAIReservationPool": "Basic YnNzYXBpdXNlcjpCc3NhITIzJA==",
    "EAI_AUTHORIZATION": "Basic YnNzYXBpdXNlcjpCc3NhITIzJA==",
    "BA_AUTHORIZATION": "Basic ZW9jLWludDpGY1ZHQkhncUpKZDdleTdS",
    "BA_AUTHORIZATION_CC": "Basic dHNjOkd0M3RKRURGN3U=",
    "enumAuth": "Basic YXBwLWVvYzphcHAtZW9j",
    "GET_NUMBER_URL": "http://eai.int.itservices.lan:8080/oss-core-ws/rest/nmext-adv/ExtendedNMService",
    "GET_MOBILE_NUMBER_URL":"https://sso.int.itservices.lan/oauth2",
    "tykAuth": "Basic aF9VRVZqOWV0R1pqclE4WXlzQWZZQTAyRWhVYTpweFVvZnJpSzFXUjVueXozRGZhWDIxNWg0cllh",
    "base64UsernameConverted":"cHJhc29iaC5uYWlyQHQtbW9iaWxlLm5sQGJ1c2luZXNzLnRlbGUyLm5s",
    "base64PasswordConverted":"QWJjZDEyMzQ=",
    "mobileNumberURL":"https://tss.int.tele2.nl/tsc/voice/groups",
    "POM_URL":"https://tibco-b.aws-tmnl.local:8301/"
}
UAT = {
    "LOGIN_URL": "https://tsc.uat.odido.nl/",
    "BSCSID":"1.18074247",
    "BROWSER": "chrome",
    "DELAY": "1",
    "VALID_USERNAME": "prasobh.nair@t-mobile.nl",
    "VALID_PASSWORD": "Abcd1234",
    "INVALID_USERNAME": "abc@t-mobile.com",
    "INVALID_PASSWORD": "qwerty123",
    "FIRST_NAME": "Mathéo",
    "BASIC_FO_LAST_NAME": "Mátyás",
    "Update_BASIC_FO_LAST_NAME": "Agnès",
    "BASIC_MO_LAST_NAME": "Hölmö",
    "BASIC_FMC_LAST_NAME": "Özcan",
    "IVR_NAME": "IVR Jokūbas",
    "Update_IVR_NAME": "IVR Agnès",
    "HG_NAME": "HG KŠthe",
    "Update_HG_NAME": "HG Asbjørn",
    "FLEX_DEVICE_NAME": "FLEX Van Buren",
    "Update_FLEX_DEVICE_NAME": "FLEX váńbúŕéń",
    "DEVICE_NAME": "DECT d3(7",
    "Update_DECT_DEVICE_NAME": "DT Renée",
    "FAX_NAME": "FAX Noël",
    "Update_FAX_NAME": "FAX Sørina",
    "CC_NAME": "CC François",
    "Update_CC_NAME": "CC Mary-Jo",
    "PASSWORD": "ABcd@#123456",
    "Update_PASSWORD": "ABcd@#456789",
    "COUNT": "3060",
    "BP_URL":"https://tsc.uat.odido.nl/hv/service",
    "MainURL":"https://tsc.uat.odido.nl/hv/groups",
    "GROUP_TAB": "https://tsc.uat.odido.nl/hv/groups/455852171/settings",
    "USER_TAB": "https://tsc.uat.odido.nl/hv/groups/455852171/users",
    "IVR_TAB": "https://tsc.uat.odido.nl/hv/groups/455852171/ivrs",
    "HG_TAB": "https://tsc.uat.odido.nl/hv/groups/455852171/hunt_groups",
    "DECT_TAB": "https://tsc.uat.odido.nl/hv/groups/455852171/multi_user_devices",
    "FLEX_TAB": "https://tsc.uat.odido.nl/hv/groups/455852171/flex",
    "FAX_TAB": "https://tsc.uat.odido.nl/hv/groups/455852171/fax_to_emails",
    "CC_TAB": "https://tsc.uat.odido.nl/hv/groups/455852171/call_centers",
    "BASE_URL": "https://eoc.uat.itservices.lan/eoc/uws/v1/order",
    "OrderLink": "https://eoc-om.uat.itservices.lan/om/#/order",
    "createOrderURLGRP": "https://eoc.uat.itservices.lan/eoc/serviceOrderingManagement/v1",
    "SR_URL": "https://eoc.uat.itservices.lan/eoc/sr/v1/service",
    "EAI_URL": "https://eai.uat.itservices.lan/oss-core-ws/rest/inv",
    "reservationPoolURL": "https://eai.uat.itservices.lan/oss-core-ws/rest/tmfnm-adv/ResourcePoolManagement",
    "eaiPortOut": "https://eai.uat.itservices.lan/oss-core-ws/rest",
    "createOrderURL": "https://eoc.uat.itservices.lan/eoc",
    "enumCheckURL": "http://mw.uat.itservices.lan:5180/rest/VTEOC/Incoming/Flows/Routing",
    "numberStatusCheckURL": "https://eai.uat.itservices.lan/oss-core-ws/rest/onm/listnm",
    "CHECK_WORKFLOW_URL": "https://eoc.uat.itservices.lan/eoc/uws/v1/fpi",
    "MessageLogURL": "https://eoc.uat.itservices.lan/eoc/logManagement/v1",
    "ErrorStatusLogURL": "https://eoc.uat.itservices.lan/eoc/logManagement/v1",
    "BROADSOFT_URL": "http://nr-workers-staging.itservices.lan/api/Voice/v1",
    "ACISION_URL": "http://nr-workers-staging.itservices.lan/api/Voicemail/v1",
    "numberCheckEAI": "https://eai.uat.itservices.lan/oss-core-ws/rest/onm/number",
    "CHECK_ORDER_URL": "https://eoc.uat.itservices.lan/eoc/uws/v1/order",
    "eaiNumberCheckURL": "https://eai.uat.itservices.lan/oss-core-ws/rest/onm/number",
    "eaiReservationURL": "https://eai.uat.itservices.lan/oss-core-ws/rest/tmfnm-adv",
    "AUTHORIZATION": "Basic c3ZjX2NvbXVzZXI6ZXFDU0NxPmU4Iw==",
    "authEAIReservationPool": "Basic YnNzYXBpdXNlcjpCc3NhITIzJA==",
    "EAI_AUTHORIZATION": "Basic YnNzYXBpdXNlcjpCc3NhITIzJA==",
    "BA_AUTHORIZATION": "Basic ZW9jLWludDpGY1ZHQkhncUpKZDdleTdS",
    "BA_AUTHORIZATION_CC": "Basic dHNjOkd0M3RKRURGN3U=",
    "enumAuth": "Basic YXBwLWVvYzp4WWFBOXVScG5zM2h4Q044dTVGdg==",
    "GET_NUMBER_URL": "https://eai.uat.itservices.lan/oss-core-ws/rest/nmext-adv/ExtendedNMService",
    "GET_MOBILE_NUMBER_URL":"https://https://sso.uat.odido.nl/oauth2",
    "tykAuth":"Basic dlVmMks3bHN6WEVtaE1HdnRqWVpjQzg5OGtFYTpXQmZQOXQ1N3JvcWhsU3FuTlhQV3BQZ2VPR01h",
    "base64UsernameConverted":"cHJhc29iaC5uYWlyQHQtbW9iaWxlLm5sQGJ1c2luZXNzLnRlbGUyLm5s",
    "base64PasswordConverted":"QWJjZDEyMzQ=",
    "mobileNumberURL":"https://tss.uat.tele2.nl/tsc/voice/groups",
    "POM_URL":"https://tibco-a.aws-tmnl.local:8201/"
}
